<a href="https://colab.research.google.com/github/ihagoSantos/special-topics-in-machine-learning/blob/main/03_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GPT

O código é adaptado [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) criado por Apoorv Nandan.

Ref.: David Foster. Generative Deep Learning. O'Reilly Media; 2nd ed. 2023.

Link para o original: https://github.com/davidADSP/Generative_Deep_Learning_2nd_Edition/blob/main/notebooks/09_transformer/gpt/gpt.ipynb

In [3]:
!mkdir checkpoint
!mkdir models

In [4]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [9]:
VOCAB_SIZE = 10000
MAX_LEN = 80 # Tamanho máximo de palavras do texto produzido
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2 # Num de attention heads
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [6]:
# Load the full dataset
with open("winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [7]:
len(wine_data)

129971

In [8]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [10]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [11]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [12]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.



## 2. Tokenize the data <a name="tokenize"></a>

In [13]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [14]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [15]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [16]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [17]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [18]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [19]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [20]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [21]:
example_input_output = train_ds.take(1).get_single_element()

In [22]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,   42,    2,  513,   42,    2, 2655,    5,  374,
       1909,    2,    6,    7,   13,   38,    5,  718,   58,    4,   15,
         41,    8,  180,  120,    3,  136,   77,    5,  237,   30,    4,
         79,   13,    8,  273,  269,   17,   12,  197,    7,   25,  113,
       2682,  891,   51,    6,   38,   53,   22, 8599,  915,    4,   88,
          6,  329,    3,   79,   13,    8,  108,    9,  217,    4,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [23]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,   42,    2,  513,   42,    2, 2655,    5,  374, 1909,
          2,    6,    7,   13,   38,    5,  718,   58,    4,   15,   41,
          8,  180,  120,    3,  136,   77,    5,  237,   30,    4,   79,
         13,    8,  273,  269,   17,   12,  197,    7,   25,  113, 2682,
        891,   51,    6,   38,   53,   22, 8599,  915,    4,   88,    6,
        329,    3,   79,   13,    8,  108,    9,  217,    4,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. Create the causal attention mask function <a name="causal"></a>

In [24]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [25]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [26]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [27]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [28]:
gpt.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, None)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ token_and_position_embedding    │ (None, None, 256)      │     2,580,480 │
│ (TokenAndPositionEmbedding)     │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block               │ [(None, None, 256),    │       658,688 │
│ (TransformerBlock)              │ (None, 2, None, None)] │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, None, 10000)    │     2,570,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,809,168 (22.16 MB)

 Trainable params: 5,809,168 (22.16 MB)

 Non-trainable params: 0 (0.00 B)

In [29]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [30]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [31]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.weights.h5",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [32]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4060/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2.6029
generated text:
wine review : france : bordeaux : bordeaux - style red blend : this is a big wine , big with its ripe fruit , opulent overripe tannins and rich with superripe black currant fruit . it has brings out the structure to a dark core , almost sweet flavors of tannins that bring out some toasted almonds and soft acidity . it is the potential to be ready to drink . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 201s 47ms/step - loss: 2.6028
Epoch 2/5
4059/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.9782
generated text:
wine review : france : burgundy : chardonnay : a touch unbalanced , this wine from the wood - aged cradling of neutral oak , it ' s a balanced wine that could almost be just beginning to show great fruitiness with its structure and elegance . it is still young and will take time to give it out its age . drink from 2017 . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 104s 26ms/step - loss: 1.9782
Epoch 3/5
4059/4060 ━

In [33]:
# Save the final model
gpt.save("gpt.keras")

# 3. Generate text using the Transformer

In [34]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

**Gerando texto**

Podemos gerar um novo texto aplicando o seguinte processo:

* Alimente a rede com uma sequência de palavras existente e peça para prever a palavra seguinte.

* Anexe esta palavra à sequência existente e repita.

A rede produzirá um conjunto de probabilidades para cada palavra da qual podemos fazer uma amostra

In [35]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : california : pinot noir : sharp and lively on the finish for an unfussy nose , this pinot shows red cherry and pomegranate flavors evolving with notes of tamarind from sandalwood and fine - grained barrels and nuanced oak . 



In [36]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : veneto : glera : this refreshing prosecco superiore opens with subdued aromas of peach and green apple . it ' s a lively , fresh and lively , with a bright , frothy mousse and a light touch of sweet sage . 



Ambos são semelhantes a uma crítica de vinhos do conjunto de treinamento original.

Ambos abrem com a região e o tipo de vinho, e o tipo de vinho permanece consistente ao longo da passagem (por exemplo, não muda de cor no meio).

O texto gerado com temperatura 1,0 é mais aventureiro e, portanto, menos preciso do que o exemplo com temperatura 0,5.

A geração de múltiplas amostras com temperatura 1,0 levará, portanto, a mais variedade, pois o modelo amostra uma distribuição de probabilidade com maior variância.

In [37]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : mosel : riesling : fresh and fruity , this riesling has a slightly off - dry , crisp apple and pear flavors . it ' s balanced with a crisp , refreshing finish . 



::   	100.0%
-:   	0.0%
grosso:   	0.0%
zealand:   	0.0%
roxo:   	0.0%
--------



mosel:   	97.26000213623047%
nahe:   	1.1699999570846558%
rheingau:   	1.1200000047683716%
pfalz:   	0.23000000417232513%
rheinhessen:   	0.20000000298023224%
--------



::   	99.94999694824219%
-:   	0.05000000074505806%
grosso:   	0.0%
nose:   	0.0%
blanca:   	0.0%
--------



riesling:   	100.0%
pinot:   	0.0%
saar:   	0.0%
white:   	0.0%
sparkling:   	0.0%
--------



::   	100.0%
-:   	0.0%
blanc:   	0.0%
grosso:   	0.0%
blend:   	0.0%
--------



while:   	21.110000610351562%
this:   	18.75%
the:   	15.65999984741211%
a:   	8.640000343322754%
fresh:   	7.539999961853027%
--------



and:   	48.43000030517578%
,:   	29.81999969482422%
apple:   	7.559999942779541%
lemon:   	3.009999990463257%
tangerine:   	2.809999942779541%
--------



fruity:   	73.4800033569336%
floral:   	7.199999809265137%
juicy:   	5.21999979019165%
crisp:   	3.7899999618530273%
cheery:   	1.1299999952316284%
--------



,:   	97.7699966430664%
on:   	2.0199999809265137%
in:   	0.10000000149011612%
with:   	0.07000000029802322%
yet:   	0.009999999776482582%
--------



this:   	91.70999908447266%
with:   	8.069999694824219%
yet:   	0.10999999940395355%
but:   	0.03999999910593033%
it:   	0.03999999910593033%
--------



off:   	27.280000686645508%
dry:   	19.559999465942383%
is:   	18.670000076293945%
light:   	7.110000133514404%
riesling:   	3.2699999809265137%
--------



is:   	67.08999633789062%
has:   	15.600000381469727%
offers:   	6.590000152587891%
balances:   	2.799999952316284%
from:   	1.7300000190734863%
--------



a:   	94.72000122070312%
an:   	1.75%
loads:   	0.699999988079071%
forward:   	0.4399999976158142%
delicate:   	0.3799999952316284%
--------



delicate:   	39.4900016784668%
light:   	17.520000457763672%
slightly:   	12.350000381469727%
floral:   	3.119999885559082%
crisp:   	3.069999933242798%
--------



sweet:   	45.849998474121094%
floral:   	15.149999618530273%
savory:   	8.079999923706055%
confected:   	6.050000190734863%
candied:   	4.900000095367432%
--------



-:   	100.0%
dry:   	0.0%
set:   	0.0%
,:   	0.0%
touch:   	0.0%
--------



dry:   	100.0%
[UNK]:   	0.0%
sweet:   	0.0%
balance:   	0.0%
gold:   	0.0%
--------



riesling:   	42.630001068115234%
,:   	42.47999954223633%
palate:   	6.599999904632568%
style:   	2.049999952316284%
finish:   	1.7599999904632568%
--------



crisp:   	36.130001068115234%
minerally:   	18.889999389648438%
slightly:   	17.3799991607666%
steely:   	7.260000228881836%
honeyed:   	3.240000009536743%
--------



,:   	56.56999969482422%
apple:   	18.360000610351562%
white:   	12.789999961853027%
and:   	7.690000057220459%
wine:   	0.8899999856948853%
--------



and:   	89.19000244140625%
-:   	9.170000076293945%
,:   	1.5399999618530273%
flavor:   	0.07000000029802322%
flavors:   	0.009999999776482582%
--------



pear:   	49.33000183105469%
citrus:   	22.350000381469727%
lemon:   	12.0%
lime:   	7.099999904632568%
peach:   	2.3399999141693115%
--------



flavors:   	98.38999938964844%
notes:   	1.2699999809265137%
aromas:   	0.2199999988079071%
-:   	0.05999999865889549%
fruit:   	0.03999999910593033%
--------



.:   	77.6500015258789%
,:   	15.609999656677246%
that:   	5.849999904632568%
accented:   	0.47999998927116394%
and:   	0.10999999940395355%
--------



it:   	95.04000091552734%
the:   	3.819999933242798%
a:   	0.6600000262260437%
there:   	0.14000000059604645%
fresh:   	0.03999999910593033%
--------



':   	99.79000091552734%
finishes:   	0.15000000596046448%
is:   	0.03999999910593033%
has:   	0.0%
balances:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
d:   	0.0%
':   	0.0%
[UNK]:   	0.0%
--------



a:   	73.30999755859375%
an:   	5.110000133514404%
not:   	4.760000228881836%
light:   	2.2300000190734863%
refreshing:   	1.7200000286102295%
--------



and:   	34.2400016784668%
,:   	32.77000045776367%
with:   	19.100000381469727%
by:   	11.869999885559082%
in:   	1.2699999809265137%
--------



a:   	83.63999938964844%
crisp:   	7.829999923706055%
fresh:   	1.5199999809265137%
brisk:   	1.4500000476837158%
refreshing:   	1.190000057220459%
--------



crisp:   	15.609999656677246%
refreshing:   	14.8100004196167%
delicate:   	13.289999961853027%
brisk:   	7.440000057220459%
touch:   	6.019999980926514%
--------



,:   	99.44999694824219%
finish:   	0.15000000596046448%
acidity:   	0.12999999523162842%
streak:   	0.07000000029802322%
edge:   	0.07000000029802322%
--------



clean:   	67.0999984741211%
refreshing:   	16.90999984741211%
lemony:   	8.180000305175781%
fresh:   	1.5499999523162842%
citrusy:   	1.4800000190734863%
--------



finish:   	75.2300033569336%
acidity:   	7.610000133514404%
,:   	6.920000076293945%
feel:   	2.2200000286102295%
mouthfeel:   	1.8799999952316284%
--------



.:   	98.63999938964844%
that:   	0.8100000023841858%
,:   	0.5199999809265137%
with:   	0.019999999552965164%
marked:   	0.009999999776482582%
--------



:   	95.29000091552734%
drink:   	4.5%
it:   	0.10999999940395355%
enjoy:   	0.029999999329447746%
the:   	0.029999999329447746%
--------



Ref.: David Foster. Generative Deep Learning. O'Reilly Media; 2nd ed. 2023.

Link para o original: https://github.com/davidADSP/Generative_Deep_Learning_2nd_Edition/blob/main/notebooks/09_transformer/gpt/gpt.ipynb